### ISSUE TITLE
v0.2.5 - 0.2.7 only display a blank screen on SFOS < 3.1.0

### ISSUE THREAD

**Issue by Olf0** [grumpycat3051/harbour-phillis#6]
PHillis versions 0.2.5, 0.2.6 and 0.2.7 just display a blank screen on SailfishOS releases below 3.1.0.
Actually there is a dim background texture shown, which can be more easily detected when turning the device between portrait and landscape orientation.
Nevertheless PHillis is completely dysfunctional.

Side note: The earlier [version 0.2.4 is reported to fail in a different manner](https://openrepos.net/comment/31048#comment-31048) and [version 0.2.3 in a way, which seems to be a server error](https://openrepos.net/comment/31048#comment-31048).

@Pohli provided [the output of PHillis 0.2.7](https://openrepos.net/comment/31035#comment-31035) when started at the command line:

    [nemo@Sailfish ~]$ harbour-phillis
    [D] unknown:0 - Using Wayland-EGL
    [D] unknown:0 - "No carrier"
    [W] unknown:0 - Could not find any zN.M subdirs!
    [W] unknown:0 - Theme dir "/usr/share/themes/jolla-ambient/meegotouch/z1.0/" does not exist
    [D] unknown:0 - load key /access/restrict type bool
    [D] unknown:0 - load key /account/username type QString
    [D] unknown:0 - load key /account/login_on_app_start type bool
    [W] modifyPageStack:113 - Error while modifying page stack: Error: Error while loading page: file:///usr/share/harbour-phillis/qml/pages/StartPage.qml:195 Type NavigationItem unavailable file:///usr/share/harbour-phillis/qml/pages/NavigationItem.qml:40 Icon is not a type
    [W] unknown:483 - file:///usr/lib/qt5/qml/Sailfish/Silica/PageStack.js:483: Error: Error while loading page: file:///usr/share/harbour-phillis/qml/pages/StartPage.qml:195 Type NavigationItem unavailable file:///usr/share/harbour-phillis/qml/pages/NavigationItem.qml:40 Icon is not a type
    [D] unknown:0 - load key /disclaimer_accepted type bool
    [D] unknown:0 - clearing cookies
    [D] unknown:0 - added QNetworkCookie("age_verified=1; expires=Thu, 24-Oct-2019 15:28:46 GMT; domain=.pornhub.com; path=/")
    [D] unknown:0 - start download of "https://www.pornhub.com"
    [D] onStatusChanged:63 - completed error=0
    [D] unknown:0 - # 6
    [D] unknown:0 - QNetworkCookie("age_verified=1; expires=Thu, 24-Oct-2019 15:28:46 GMT; domain=.pornhub.com; path=/")
    [D] unknown:0 - QNetworkCookie("ua=d3ce4e27b518018f42cb5a8a22daabe9; expires=Thu, 15-Aug-2069 06:57:34 GMT; domain=.pornhub.com; path=/")
    [D] unknown:0 - QNetworkCookie("platform=pc; expires=Thu, 15-Aug-2069 06:57:34 GMT; domain=.pornhub.com; path=/")
    [D] unknown:0 - QNetworkCookie("bs=86fqeyaiftw488f3fagd9y1mnmvuygso; expires=Sat, 12-Aug-2079 06:57:34 GMT; domain=.pornhub.com; path=/")
    [D] unknown:0 - QNetworkCookie("ss=924235716931651756; expires=Thu, 22-Oct-2020 15:28:47 GMT; domain=.pornhub.com; path=/")
    [D] unknown:0 - QNetworkCookie("RNLBSERVERID=ded6277; domain=www.pornhub.com; path=/")
    [D] updateSessionHtml:447 - login token=MTU3MTg0NDUyN5EozZuLe5o4G0KbDkv6S0lXVbGIJdljLKp9TWidDF_sk3AynrlvPBOc4mPB29mmGxsv6Bq3HZnSowT_U8-BOJI.

@grumpycat3051 concluded that [this issue stems from  the file `Icon.qml` not being found](https://openrepos.net/comment/31037#comment-31037), which is located in `/usr/lib/qt5/qml/Sailfish/Silica/Icon.qml` on his device with SailfishOS 3.1.0.

But [there definitely is no `/usr/lib/qt5/qml/Sailfish/Silica/Icon.qml`](https://openrepos.net/comment/31038#comment-31038) on a regular installation of SailfishOS below 3.1.0.

Tested with SailfishOS 2.2.1, 3.0.1 and 3.0.3 (on Jolla 1 phones and an Xperia X, though the device used does not seem to make any difference).

**Comment by Olf0** [comment]
I followed [the advice of testing older versions of PHillis](https://openrepos.net/comment/31053#comment-31053):

1. I intended to clean `home/nemo/.local/share/harbour-phillis` before downgrading, but this directory does not exist (although I have PHillis installed and updated since it first release, currently v0.2.7).
2. Uninstalled PHillis.
3. Installed PHillis 0.1, which is working.
4. Installed PHillis 0.2.1, which is working.
5. Installed PHillis 0.2.2, which is working.
4. Installed PHillis 0.2.3, which is working.
4. Installed PHillis 0.2.4, which is working.
4. Installed PHillis 0.2.5, which shows this issue (blank screen), exactly as PHillis 0.2.6 and 0.2.7 do.

Tested with SailfishOS 2.2.1 (on a Jolla 1 phone).

Notes:
* With PHillis 0.1, 0.2.1, 0.2.2 and 0.2.3, I was unable to play any video (nothing happened when hitting the play button, but the video reloaded shortly when moving the slider).
* With PHillis 0.2.4, tapping on a video on the grid does not select it.
* This is exactly what @Pohli [reported for SailfishOS 3.0.1](https://openrepos.net/comment/31048#comment-31048).

Hence unfortunately no version of PHillis is currently working for me (but 0.2.x < 0.2.5 definitely did in the past).

**Comment by grumpycat3051** [comment]
Thank your thorough analysis. As suspected 0.2.5 replaced Image with Icon which causes failures for SFOS < 3.1 for all versions thereafter.

I have pushed some changes that should allow you run the app again and I would like for you to try them out.

**Comment by Olf0** [comment]
Sure, but as the [changes are altering seven files](https://github.com/grumpycat3051/harbour-phillis/commit/ee739d3a68091cc148a50b25a110dee75e623bc9) and there are [subsequent changes](https://github.com/grumpycat3051/harbour-phillis/commits/master), I would have to compile and package it anew.  As I have never done this before with PHillis and deviating from your compiling and packaging procedures may introduce new issues, please provide an RPM (e g. Git-tagged and rpm-versioned as **0.2.7.1**) by creating a release [at PHillis' releases page](https://github.com/grumpycat3051/harbour-phillis/releases) and uploading the RPM there (by *clicking on the tag -> "Edit release" -> "Attach binaries by dropping them here or selecting them."*).

This would enable all users of PHillis to test this beta RPM by downloading it from the [releases page](https://github.com/grumpycat3051/harbour-phillis/releases) and installing it (manually or per Storeman's "local RPMs" category).

**Comment by grumpycat3051** [comment]
Nice, didn't know I could upload binaries to Github releases.

**Comment by Olf0** [comment]
Thanks, this issue is fixed in the [test-release 0.2.7.1](https://github.com/grumpycat3051/harbour-phillis/releases/tag/v0.2.7.1), thus closing.

Note that the ["cannot select video"-issue](https://github.com/grumpycat3051/harbour-phillis/issues/7) is still present, hence I will open one for that.
