### ISSUE TITLE
Cannot select any video in v0.2.4 - 0.2.7.1 on SFOS < 3.1.0

### ISSUE THREAD

**Issue by Olf0** [grumpycat3051/harbour-phillis#7]
As originally reported as a [side note in issue \#6](https://github.com/grumpycat3051/harbour-phillis/issues/6#issuecomment-546552670) and by @Pohli [at OpenRepos](https://openrepos.net/comment/31048#comment-31048):
With PHillis 0.2.4 to 0.2.7.1, tapping on a video (i.e., on any grid) does not select it.

Note that with PHillis 0.1, 0.2.1, 0.2.2 and 0.2.3, I am able to select all videos, but unable to play any video (nothing happens when hitting the play button, but the video reloads shortly when moving the slider).

Tested with SailfishOS 2.2.1, 3.0.1 and 3.0.3 (on Jolla 1 phones and an Xperia X, though the device used does not seem to make any difference).

Hence unfortunately no version of PHillis is currently working for me (but 0.2.x < 0.2.4 definitely did in the past).

**Comment by grumpycat3051** [comment]
Please start the app from the command line and provide the debug log.

**Comment by Olf0** [comment]
... I was already on the way.
Started [PHillis 0.2.7.1](https://github.com/grumpycat3051/harbour-phillis/releases/tag/v0.2.7.1) at the command line as user *nemo* per `harbour-phillis 2>&1 | tee phillis-0.2.7.1.log.txt`, went to *Videos -> Hottest* and tapped three times on the first video at the grid, followed by closing PHillis per top-swipe.
Output file: [phillis-0.2.7.1.log.txt](https://github.com/grumpycat3051/harbour-phillis/files/3776110/phillis-0.2.7.1.log.txt)
One can nicely see the three unsuccessful taps at the end of this log.

Tested on a Jolla 1 with SailfishOS 2.2.1 (*edit:*) and an Xperia X with SailfishOS 3.0.3.

**Comment by grumpycat3051** [comment]
This issue is similar to the Icon one. The app uses Nemo.KeepAlive 1.2 to prevent screen blanking while the video is playing. Previous versions used Nemo.KeepAlive 1.1. I added a fallback which does nothing in case neither version is available.

Note: vod url extraction currently doesn't work for all videos. Please do try a few if the selected one doesn't play back.

**Comment by Olf0** [comment]
> Note: vod url extraction currently doesn't work for all videos. Please do try a few if the selected one doesn't play back.

Well, "Copy URL to clipboard" in PHillis 0.2.7.1 works for me, so does downloading with such a copied video URL per Vodman.

Lets see if that works for me at the GUI of PHillis, if I am able to get this far again (as with PHillis < 0.2.4) with a future (test-) release.

**Comment by grumpycat3051** [comment]
You should try release v0.2.7.2

**Comment by Olf0** [comment]
[PHillis 0.2.7.2](https://github.com/grumpycat3051/harbour-phillis/releases/tag/v0.2.7.2) is working absolutely fine on SailfishOS 2.2.1 and 3.0.3.

Thank you!

**Comment by Pohli** [comment]
It works again for me on Jolla Phone with SFOS 3.0.1.11, thanks!
