### ISSUE TITLE
Screen blanking prevention does not work on SFOS < 3.1

### ISSUE THREAD

**Issue by Olf0** [grumpycat3051/harbour-phillis#8]
The screen blanking prevention does not work, hence the screen goes dark after the period set in the SailfishOS' *Settings -> Display -> Sleep after*.

Tested with PHillis 0.2.7.2 on an Xperia X with SailfishOS 3.0.3.

I faintly remember other SailfishOS apps have or had similar issues, e.g. Pure Maps.  IIRC the apps' wish to omit screen blanking was / is simply ignored by SailfishOS.
But OTOH I believe (but may be wrong) that the screen blanking prevention was working in PHillis < 0.2.4

If this only happens on SailfishOS < 3.1.0 (again) and is definitely not an mistake in code newly introduced in PHillis (since ca. v0.2.0), it may make sense not to invest much time to analyse the behaviour of old SailfishOS releases, but to close this issue as "won't fix".

**Comment by Olf0** [comment]
Ah, I missed [this debugging line](https://github.com/grumpycat3051/harbour-phillis/blob/297c59a2a4f170ee2083e4437d69336585ef2774/qml/pages/VideoPlayerPage.qml#L1144) being added by [commit #297c59a](https://github.com/grumpycat3051/harbour-phillis/commit/297c59a2a4f170ee2083e4437d69336585ef2774#diff-46adb58dd9e8e71a9f1c414e5de41327).
And yes, there it is [in the console output](https://github.com/grumpycat3051/harbour-phillis/files/3776412/phillis-0.2.7.2.log.txt):
`[W] _createDisplayBlanking:1144 - display blanking prevention not available`

Tested on SailfishOS 2.2.1 (Jolla 1), which IMO should support *Nemo.KeepAlive 1.1*, and screen blanking prevention failed [the same way on SailfishOS 3.0.3](https://github.com/grumpycat3051/harbour-phillis/issues/8#issue-513017431).

**Comment by grumpycat3051** [comment]
Thanks for testing, again. 

DisplayBlanking is a global in Nemo.KeepAlive 1.1 whereas it requires instantiation in Nemo.KeepAlive 1.2. The fallback code didn't take that into account :/ the original code in < 0.2.4 did, however.

Please check out release 0.2.7.3

**Comment by Olf0** [comment]
Thank you for [commit #bae7752](https://github.com/grumpycat3051/harbour-phillis/commit/bae77528d725b2375a9810c2806197b819e9d25a), fixing this issue.
[The console output](https://github.com/grumpycat3051/harbour-phillis/files/3785696/phillis-0.2.7.3.log.txt) of [PHillis 0.2.7.3](https://github.com/grumpycat3051/harbour-phillis/releases/tag/v0.2.7.3) also nicely shows this, now:
`[I] _createDisplayBlanking:1129 - Attempting to use Nemo.KeepAlive 1.2 DisplayBlanking`
`[D] _createDisplayBlanking:1143 - exception: Qt.createQmlObject(): failed to create object:`
`    file:///usr/share/harbour-phillis/qml/pages/script:2:1: module "Nemo.KeepAlive" version 1.2 is not installed`
`[I] _createDisplayBlanking:1148 - Attempting to use Nemo.KeepAlive 1.1 DisplayBlanking`
`[I] _createDisplayBlanking:1158 - Using Nemo.KeepAlive 1.1 DisplayBlanking`

Tested on SailfishOS 2.2.1 (Jolla 1).
